app:
  name: zliway
  port: 9500

program:
  key: key123

persistent:
  mysql:
    host: 192.168.204.133
    port: 3306
    database: zliway
    username: root
    password: root
    charset: utf8mb4
    max_idle_conns: 5
    max_open_conns: 10
    log_mode: info
    enable_file_log_writer: true
    log_folder: sql
  redis:
    host: 192.168.204.133
    port: 6379
    db: 2

log:
  level: info
  root_dir: ./runtime/log
  log_folder_app: app
  log_folder_server: server
  format: json
  show_line: true
  max_backups: 3
  max_size: 500
  max_age: 30
  compress: true