app:
  name: zliway
  port: 9500
  backstage_port: 9510
  token: zliway@2023
  token_header: token

persistent:
  mysql:
    host: 192.168.204.133
    port: 3306
    database: zliway
    username: root
    password: root
    charset: utf8mb4
    max_idle_conn: 5
    max_open_conn: 10
    log_mode: info
    enable_file_log_writer: true
    log_folder: sql
  redis:
    host: 192.168.204.133
    port: 6379
    db: 2

log:
  level: info
  root_dir: ./runtime/log
  log_folder_app: app
  log_folder_server: server
  format: json
  show_line: true
  max_backups: 3
  max_size: 500
  max_age: 30
  compress: true

#zliway:
#  project:
#    - app: eyesStars
#      host: stars.eyescode.top
#      cors:
#        allowedOrigins:
#          - stars.eyescode.top
#        allowedMethods:
#          - "GET"
#          - "POST"
#          - "DELETE"
#          - "PUT"
#          - "OPTION"
#        allowedHeaders: "*"
#        allowCredentials: true
#        maxAge: 360000
#      rate:
#        name: tokenBucket
#        args:
#          replenishRate: 10
#          burstCapacity: 15
#          key-resolver: ip